import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#212121",
        "surface-container-high": "#2b2b2b",
        "surface-container-highest": "#363636",
        "on-surface": "#ffffff",
        "on-surface-variant": "#c4c4c4",
        outline: "#8e8e8e",
        "outline-variant": "#444444",
        primary: "var(--color-primary, #e60000)",
        "on-primary": "#ffffff",
        "primary-container": "#4d0000",
        "on-primary-container": "#ffdad6",
        secondary: "var(--color-secondary, #ffb800)",
        "on-secondary": "#131313",
        "secondary-container": "#4d3800",
        "on-secondary-container": "#ffdf9e",
        tertiary: "#ffffff",
        "on-tertiary": "#131313",
        background: "#0e0e0e",
        "on-background": "#ffffff",
        error: "#ffb4ab",
        "on-error": "#690005",
        // Alias di compatibilità verso i vecchi nomi usati in alcuni componenti,
        // mappati sui nuovi token del design system "Phoenix Sport Pro".
        gold: "var(--color-secondary, #ffb800)",
        line: "#444444",
        base: "#0e0e0e",
        surface2: "#2b2b2b",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "2px",
        lg: "4px",
        xl: "8px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        base: "4px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["var(--font-anybody)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
